spring:
   rabbitmq:
    username: guest
    password: guest
    host: 192.168.99.100
zuul:
  sensitiveHeaders:
  ignored-patterns:
    - /**/order/env  
  routes:
   myOrder:
    path: /myOrder/**
    serviceId: order
   myConfig:
    path: /myConfig/**
    serviceId: config
#   sensitiveHeaders:
#   product: /myProduct/**
#   config: /myConfig/**  
management:
  endpoints:
    web:
      exposure:
        include: '*'    
    
