spring:
   rabbitmq:
    username: guest
    password: guest
    host: 192.168.99.100
   redis:
    port: 6379
    host: localhost   
zuul:
  sensitive-headers:
  ignored-patterns:
    - /**/order/env  
#  routes:
#   myOrder:
#    path: /myOrder/**
#    serviceId: order
#   myConfig:
#    path: /myConfig/**
#   serviceId: config
#   sensitiveHeaders:
#   product: /myProduct/**
#   config: /myConfig/**  
management:
  endpoints:
    web:
      exposure:
        include: '*'    
    
ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000
