spring:
   rabbitmq:
    username: guest
    password: guest
    host: 192.168.99.100
zuul:
  routes:
#   product: /myProduct/**
#   config: /myConfig/**
  ignored-patterns:
   -/**/order/env
   myOrder:
    path: /myOrder/**
    serviceId: order
    sensitiveHeaders:
   myConfig:
    path: /myConfig/**
    serviceId: config
    sensitiveHeaders:
management:
  endpoints:
    web:
      exposure:
        include: '*'    
    
