
spring:
  rabbitmq:
    host:  192.168.99.100
    port: 5672
    username: guest
    userpassword: guest
  application:
    name: order
  jpa:
    show-sql: true
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://127.0.0.1/SpringCloud_Sell?characterEncoding=UTF-8&useSSL=false
  cloud:
    loadbalancer:
      retry:
        enabled: true
ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000
